#!/bin/bash
cd $(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
[ -z "$1" ] && { echo "Usage: $0 [ TYPE FIELD1 FIELD2 FIELD3 ... ]"; exit; }
TYPE=$1; shift

#---------------------------------------------------------------------------------------------------------------------------------------------------
for FIELD in $@; do cat << EOF > ${TYPE}.code
			formData.${FIELD^}=		r.FormValue("${FIELD}")
EOF
done
#---------------------------------------------------------------------------------------------------------------------------------------------------
cat << EOF >> ${TYPE}.code
type ${TYPE^} struct {
	Edit		bool	\`json:"-"\` // No need to store the mode
	Id		string	\`json:"-"\` // No need to store the id, it is the filename
EOF
#---------------------------------------------------------------------------------------------------------------------------------------------------
for FIELD in $@; do cat << EOF >> ${TYPE}.code
	${FIELD^}	string
EOF
done
#---------------------------------------------------------------------------------------------------------------------------------------------------
cat << EOF >> ${TYPE}.code
}
EOF
echo ===== ${TYPE} =====
cat ${TYPE}.code
