#!/bin/bash
cd $(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
[ -z "$1" ] && { echo "Usage: $0 [ TYPE FIELD1 FIELD2 FIELD3 ... ]"; exit; }
TYPE=$1; shift

cat << EOF > ${TYPE}.form
<h1>${TYPE^}</h1>
<hr>
{{if .Edit}}
	<form method="POST">
		<label>Id: </label>{{.Id}}<br /><br />
EOF
#---------------------------------------------------------------------------------------------------------------------------------------------------
for FIELD in $@; do cat << EOF >> ${TYPE}.form
		<!--FIX THIS: Use only one -->
		<label>${FIELD^}:</label><br />		<input type="text" name="${FIELD}"	value="{{.${FIELD^}}}"><br />
		<label>${FIELD^}:</label><br />		<textarea name="${FIELD}">{{.${FIELD^}}}</textarea><br />
EOF
done
#---------------------------------------------------------------------------------------------------------------------------------------------------
cat <<EOF >> ${TYPE}.form
		<input type="submit">
	</form>
{{else}}
	<label>Id:		</label>{{.Id}}<br /><br />
EOF
#---------------------------------------------------------------------------------------------------------------------------------------------------
for FIELD in $@; do cat << EOF >> ${TYPE}.form
	<label>${FIELD^}:	</label>{{.${FIELD^}}}<br />
EOF
done
#---------------------------------------------------------------------------------------------------------------------------------------------------
cat << EOF >> ${TYPE}.form
{{end}}
EOF
#---------------------------------------------------------------------------------------------------------------------------------------------------

echo ===== ${TYPE}.form =====
cat ${TYPE}.form
